name: Analyze

on:
  pull_request:
    branches:
      - master

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{hashFiles('package-lock.json')}}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Validate commits
        run: npm run lint:commit -- --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test -- --runInBand --no-cache

      - name: Run build
        run: npm run build

      - name: Run coverage
        run: npm run test:coverage -- --runInBand --no-cache

      - name: Run codecov
        run: npx codecov
