name: Analyze

on:
  pull_request:
    branches:
      - master

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Cache dependencies
        uses: actions/cache/save@v3
        with:
          path: ~/.npm
          key: npm-${{hashFiles('package-lock.json')}}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

  commits:
    name: Commits
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Restore dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/.npm
          key: npm-${{hashFiles('package-lock.json')}}
          restore-keys: npm-

      - name: Validate commits
        run: npm run lint:commit -- --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Restore dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/.npm
          key: npm-${{hashFiles('package-lock.json')}}
          restore-keys: npm-

      - name: Run build
        run: npm run build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Restore dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/.npm
          key: npm-${{hashFiles('package-lock.json')}}
          restore-keys: npm-

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test -- --coverage --runInBand --no-cache

      - name: Cache coverage report
        uses: actions/cache/save@v3
        with:
          path: coverage
          key: coverage-${{ github.sha }}
          restore-keys: coverage-

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Restore dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/.npm
          key: npm-${{hashFiles('package-lock.json')}}
          restore-keys: npm-

      - name: Restore coverage report
        uses: actions/cache/restore@v3
        with:
          path: coverage
          key: coverage-${{ github.sha }}
          restore-keys: coverage-

      - name: Send coverage report
        run: npx codecov
